# -*- coding: utf-8 -*-
"""mrz_decoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bv3oq6vypmjgk4BGT870zYswiry298Dy
"""

!pip install pytesseract
!pip install tesseract
!sudo apt install tesseract-ocr
!pip install mrz

# place mrz.traineddata to usr/share/tesseract-ocr/tessdata

import pytesseract
from mrz.checker.td3 import TD3CodeChecker, get_country
import cv2
import json

pytesseract.pytesseract.tesseract_cmd = r'/usr/bin/tesseract'

def convert_to_date(string):
  return ".".join([string[-2:], string[2:-2], string[:2]])

def to_json(fields):
  data = {}
  fieldsName = ['surname', 'name', 'country',
                'nationality', 'birth_date',
                'expiry_date', 'sex', 'document_type',
                'document_number', 'optional_data']
  for i, key in enumerate(fieldsName) :
    data[key] = fields[i]
  data['country'] = get_country(data['country'])
  data['birth_date'] = convert_to_date(data['birth_date'])
  data['expiry_date'] = convert_to_date(data['expiry_date'])
  return json.dumps(data)


def get_mrz_data(image):
  mrz_code = pytesseract.image_to_string(image, lang="mrz")[:-2]
  td3_check = TD3CodeChecker(mrz_code)
  fields = td3_check.fields()

  return to_json(fields)

